name: CD pipeline WIP

on:
  push:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn
      - name: Clean
        run: npx rimraf ./build
      - name: lint
        run: yarn lint .
      - name: test
        run: yarn test

